# Generated by Django 4.0.2 on 2022-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercheck',
            name='current_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
