# Generated by Django 4.0.2 on 2022-08-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weathercheck_current_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercheck',
            name='endaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weathercheck',
            name='startaddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
